import React, { useState } from 'react';
import { Download, FileJson, FileText, FileBarChart, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useGetUserData } from '../hooks/useQueries';
import { toast } from 'sonner';

// ─── Export Utilities ─────────────────────────────────────────────────────────

function exportAsJSON(data: unknown, filename: string) {
  const json = JSON.stringify(data, (_, v) => (typeof v === 'bigint' ? v.toString() : v), 2);
  const blob = new Blob([json], { type: 'application/json' });
  triggerDownload(blob, filename);
}

function exportAsCSV(rows: Record<string, unknown>[], filename: string) {
  if (!rows.length) {
    toast.error('No data available to export as CSV');
    return;
  }
  const headers = Object.keys(rows[0]);
  const csvRows = [
    headers.join(','),
    ...rows.map((row) =>
      headers
        .map((h) => {
          const val = row[h];
          const str = typeof val === 'bigint' ? val.toString() : String(val ?? '');
          return `"${str.replace(/"/g, '""')}"`;
        })
        .join(',')
    ),
  ];
  const blob = new Blob([csvRows.join('\n')], { type: 'text/csv' });
  triggerDownload(blob, filename);
}

function exportAsPDF(data: unknown, filename: string) {
  const dataStr = JSON.stringify(data, (_, v) => (typeof v === 'bigint' ? v.toString() : v), 2);
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>TRANQUIL – My Data Export</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #1a1a2e; }
    h1 { color: #0d9488; border-bottom: 2px solid #0d9488; padding-bottom: 8px; }
    h2 { color: #0f766e; margin-top: 32px; }
    pre { background: #f0fdfa; border: 1px solid #99f6e4; border-radius: 8px; padding: 16px; overflow-x: auto; font-size: 12px; }
    .meta { color: #6b7280; font-size: 14px; margin-bottom: 24px; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px; }
  </style>
</head>
<body>
  <h1>🧘 TRANQUIL – My Data Export</h1>
  <p class="meta">Exported on: ${new Date().toLocaleString()} | This is a complete export of your personal mental health data.</p>
  <h2>Your Data</h2>
  <pre>${dataStr}</pre>
  <div class="footer">
    <p>This export was generated by TRANQUIL. Your data belongs to you.</p>
    <p>GDPR compliant | Indian IT Act compliant | AES-256 encrypted at rest</p>
  </div>
</body>
</html>`;
  const blob = new Blob([html], { type: 'text/html' });
  triggerDownload(blob, filename);
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ─── Component ────────────────────────────────────────────────────────────────

type ExportFormat = 'json' | 'csv' | 'pdf';

export default function DataExportCard() {
  const { data: userData, isLoading } = useGetUserData();
  const [loadingFormat, setLoadingFormat] = useState<ExportFormat | null>(null);

  const handleExport = async (format: ExportFormat) => {
    if (!userData) {
      toast.error('No data available to export. Please try again later.');
      return;
    }

    setLoadingFormat(format);
    try {
      const timestamp = new Date().toISOString().split('T')[0];

      if (format === 'json') {
        exportAsJSON(userData, `tranquil-data-${timestamp}.json`);
        toast.success('Data exported as JSON');
      } else if (format === 'csv') {
        const rows = userData.stressReadings.map((r) => ({
          timestamp: r.timestamp.toString(),
          heartRate: r.heartRate.toString(),
          skinTemp: r.skinTemp,
          motion: r.motion.toString(),
          stressLevel: r.stressLevel,
        }));
        exportAsCSV(rows, `tranquil-stress-data-${timestamp}.csv`);
        toast.success('Stress data exported as CSV');
      } else if (format === 'pdf') {
        exportAsPDF(userData, `tranquil-summary-${timestamp}.html`);
        toast.success('Data summary exported (open in browser to print as PDF)');
      }
    } catch {
      toast.error(`Failed to export data as ${format.toUpperCase()}`);
    } finally {
      setLoadingFormat(null);
    }
  };

  const formats: { id: ExportFormat; label: string; desc: string; icon: React.ReactNode }[] = [
    {
      id: 'json',
      label: 'JSON',
      desc: 'Complete data export',
      icon: <FileJson className="w-5 h-5" />,
    },
    {
      id: 'csv',
      label: 'CSV',
      desc: 'Stress readings spreadsheet',
      icon: <FileText className="w-5 h-5" />,
    },
    {
      id: 'pdf',
      label: 'PDF Summary',
      desc: 'Printable HTML report',
      icon: <FileBarChart className="w-5 h-5" />,
    },
  ];

  return (
    <div className="space-y-3">
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
        {formats.map((fmt) => (
          <button
            key={fmt.id}
            onClick={() => handleExport(fmt.id)}
            disabled={isLoading || loadingFormat !== null || !userData}
            className="flex flex-col items-center gap-2 p-4 rounded-xl border border-border bg-background hover:border-primary/50 hover:bg-primary/5 transition-all disabled:opacity-50 disabled:cursor-not-allowed group"
          >
            <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center text-primary group-hover:bg-primary/20 transition-colors">
              {loadingFormat === fmt.id ? (
                <Loader2 className="w-5 h-5 animate-spin" />
              ) : (
                fmt.icon
              )}
            </div>
            <div className="text-center">
              <p className="text-sm font-semibold text-foreground">{fmt.label}</p>
              <p className="text-xs text-muted-foreground">{fmt.desc}</p>
            </div>
          </button>
        ))}
      </div>

      {!userData && !isLoading && (
        <p className="text-xs text-muted-foreground text-center py-2">
          No data available to export yet. Start using TRANQUIL to generate data.
        </p>
      )}

      <p className="text-xs text-muted-foreground flex items-center gap-1.5">
        <Download className="w-3 h-3" />
        Files are downloaded securely to your device. No data is sent to external servers.
      </p>
    </div>
  );
}
