/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const StressLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BreathingSession = IDL.Record({
  'technique' : IDL.Text,
  'durationSeconds' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'avgWeeklyStressScore' : IDL.Float64,
  'totalMoodEntries' : IDL.Nat,
  'totalBreathingSessions' : IDL.Nat,
  'avatarId' : IDL.Nat,
});
export const StressReading = IDL.Record({
  'stressLevel' : StressLevel,
  'heartRate' : IDL.Nat,
  'skinTemp' : IDL.Float64,
  'timestamp' : IDL.Int,
  'motion' : IDL.Nat,
});
export const MoodEntry = IDL.Record({
  'mood' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
});
export const ReminderPreferences = IDL.Record({
  'breaks' : IDL.Bool,
  'intervals' : IDL.Nat,
  'hydration' : IDL.Bool,
  'stretch' : IDL.Bool,
});
export const SleepEntry = IDL.Record({
  'bedtime' : IDL.Int,
  'wakeTime' : IDL.Int,
  'durationMinutes' : IDL.Nat,
  'timestamp' : IDL.Int,
  'qualityRating' : IDL.Nat,
});
export const TipCard = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const VibrationCommand = IDL.Record({
  'pattern' : IDL.Text,
  'timestamp' : IDL.Int,
  'intensity' : IDL.Nat,
});
export const UserDataView = IDL.Record({
  'reminderPrefs' : ReminderPreferences,
  'sleepEntries' : IDL.Vec(SleepEntry),
  'moodEntries' : IDL.Vec(MoodEntry),
  'breathingSessions' : IDL.Vec(BreathingSession),
  'vibrationCommands' : IDL.Vec(VibrationCommand),
  'stressReadings' : IDL.Vec(StressReading),
  'profile' : UserProfile,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBreathingSession' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addMoodEntry' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'addSleepEntry' : IDL.Func([IDL.Int, IDL.Int, IDL.Nat, IDL.Nat], [], []),
  'addStressReading' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Nat, StressLevel],
      [],
      [],
    ),
  'addVibrationCommand' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getBreathingSessions' : IDL.Func([], [IDL.Vec(BreathingSession)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLatestStressReading' : IDL.Func([], [IDL.Opt(StressReading)], ['query']),
  'getMoodEntriesThisWeek' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
  'getReadingsWithTip' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StressReading)],
      ['query'],
    ),
  'getReminderPrefs' : IDL.Func([], [ReminderPreferences], ['query']),
  'getSleepEntries' : IDL.Func([], [IDL.Vec(SleepEntry)], ['query']),
  'getTips' : IDL.Func([], [IDL.Vec(TipCard)], ['query']),
  'getUserData' : IDL.Func([], [IDL.Opt(UserDataView)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVibrationCommands' : IDL.Func([], [IDL.Vec(VibrationCommand)], ['query']),
  'getWeeklyStressAnalytics' : IDL.Func(
      [],
      [IDL.Vec(StressReading)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateReminderPrefs' : IDL.Func(
      [IDL.Bool, IDL.Bool, IDL.Bool, IDL.Nat],
      [],
      [],
    ),
  'updateUserProfile' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const StressLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BreathingSession = IDL.Record({
    'technique' : IDL.Text,
    'durationSeconds' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'avgWeeklyStressScore' : IDL.Float64,
    'totalMoodEntries' : IDL.Nat,
    'totalBreathingSessions' : IDL.Nat,
    'avatarId' : IDL.Nat,
  });
  const StressReading = IDL.Record({
    'stressLevel' : StressLevel,
    'heartRate' : IDL.Nat,
    'skinTemp' : IDL.Float64,
    'timestamp' : IDL.Int,
    'motion' : IDL.Nat,
  });
  const MoodEntry = IDL.Record({
    'mood' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
  });
  const ReminderPreferences = IDL.Record({
    'breaks' : IDL.Bool,
    'intervals' : IDL.Nat,
    'hydration' : IDL.Bool,
    'stretch' : IDL.Bool,
  });
  const SleepEntry = IDL.Record({
    'bedtime' : IDL.Int,
    'wakeTime' : IDL.Int,
    'durationMinutes' : IDL.Nat,
    'timestamp' : IDL.Int,
    'qualityRating' : IDL.Nat,
  });
  const TipCard = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const VibrationCommand = IDL.Record({
    'pattern' : IDL.Text,
    'timestamp' : IDL.Int,
    'intensity' : IDL.Nat,
  });
  const UserDataView = IDL.Record({
    'reminderPrefs' : ReminderPreferences,
    'sleepEntries' : IDL.Vec(SleepEntry),
    'moodEntries' : IDL.Vec(MoodEntry),
    'breathingSessions' : IDL.Vec(BreathingSession),
    'vibrationCommands' : IDL.Vec(VibrationCommand),
    'stressReadings' : IDL.Vec(StressReading),
    'profile' : UserProfile,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBreathingSession' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addMoodEntry' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'addSleepEntry' : IDL.Func([IDL.Int, IDL.Int, IDL.Nat, IDL.Nat], [], []),
    'addStressReading' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Nat, StressLevel],
        [],
        [],
      ),
    'addVibrationCommand' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getBreathingSessions' : IDL.Func(
        [],
        [IDL.Vec(BreathingSession)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLatestStressReading' : IDL.Func(
        [],
        [IDL.Opt(StressReading)],
        ['query'],
      ),
    'getMoodEntriesThisWeek' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
    'getReadingsWithTip' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StressReading)],
        ['query'],
      ),
    'getReminderPrefs' : IDL.Func([], [ReminderPreferences], ['query']),
    'getSleepEntries' : IDL.Func([], [IDL.Vec(SleepEntry)], ['query']),
    'getTips' : IDL.Func([], [IDL.Vec(TipCard)], ['query']),
    'getUserData' : IDL.Func([], [IDL.Opt(UserDataView)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVibrationCommands' : IDL.Func(
        [],
        [IDL.Vec(VibrationCommand)],
        ['query'],
      ),
    'getWeeklyStressAnalytics' : IDL.Func(
        [],
        [IDL.Vec(StressReading)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateReminderPrefs' : IDL.Func(
        [IDL.Bool, IDL.Bool, IDL.Bool, IDL.Nat],
        [],
        [],
      ),
    'updateUserProfile' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };