/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BreathingSession {
  'technique' : string,
  'durationSeconds' : bigint,
  'timestamp' : bigint,
}
export interface MoodEntry {
  'mood' : string,
  'note' : [] | [string],
  'timestamp' : bigint,
}
export interface ReminderPreferences {
  'breaks' : boolean,
  'intervals' : bigint,
  'hydration' : boolean,
  'stretch' : boolean,
}
export interface SleepEntry {
  'bedtime' : bigint,
  'wakeTime' : bigint,
  'durationMinutes' : bigint,
  'timestamp' : bigint,
  'qualityRating' : bigint,
}
export type StressLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface StressReading {
  'stressLevel' : StressLevel,
  'heartRate' : bigint,
  'skinTemp' : number,
  'timestamp' : bigint,
  'motion' : bigint,
}
export interface TipCard {
  'title' : string,
  'description' : string,
  'category' : string,
}
export interface UserDataView {
  'reminderPrefs' : ReminderPreferences,
  'sleepEntries' : Array<SleepEntry>,
  'moodEntries' : Array<MoodEntry>,
  'breathingSessions' : Array<BreathingSession>,
  'vibrationCommands' : Array<VibrationCommand>,
  'stressReadings' : Array<StressReading>,
  'profile' : UserProfile,
}
export interface UserProfile {
  'name' : string,
  'avgWeeklyStressScore' : number,
  'totalMoodEntries' : bigint,
  'totalBreathingSessions' : bigint,
  'avatarId' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VibrationCommand {
  'pattern' : string,
  'timestamp' : bigint,
  'intensity' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBreathingSession' : ActorMethod<[string, bigint], undefined>,
  'addMoodEntry' : ActorMethod<[string, [] | [string]], undefined>,
  'addSleepEntry' : ActorMethod<[bigint, bigint, bigint, bigint], undefined>,
  'addStressReading' : ActorMethod<
    [bigint, number, bigint, StressLevel],
    undefined
  >,
  'addVibrationCommand' : ActorMethod<[string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getBreathingSessions' : ActorMethod<[], Array<BreathingSession>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLatestStressReading' : ActorMethod<[], [] | [StressReading]>,
  'getMoodEntriesThisWeek' : ActorMethod<[], Array<MoodEntry>>,
  'getReadingsWithTip' : ActorMethod<[string], Array<StressReading>>,
  'getReminderPrefs' : ActorMethod<[], ReminderPreferences>,
  'getSleepEntries' : ActorMethod<[], Array<SleepEntry>>,
  'getTips' : ActorMethod<[], Array<TipCard>>,
  'getUserData' : ActorMethod<[], [] | [UserDataView]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVibrationCommands' : ActorMethod<[], Array<VibrationCommand>>,
  'getWeeklyStressAnalytics' : ActorMethod<[], Array<StressReading>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateReminderPrefs' : ActorMethod<
    [boolean, boolean, boolean, bigint],
    undefined
  >,
  'updateUserProfile' : ActorMethod<[string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];